################################
# WEBSOCKET
################################
websocket {
  port: 8222
  no_tls: true
}

################################
# JETSTREAM
################################
jetstream {
  store_dir: /data/jetstream
}

################################
# ACCOUNTS
################################
accounts {

  ################################
  # SYSTEM ACCOUNT
  ################################
  SYS: {
    users: [
      { user: "sys", password: "sys" }
    ]
    exports: [
      {
        stream: "$SYS.ACCOUNT.PNM.>"
        accounts: [PNM]
      }
    ]
  }

  ################################
  # PNM ACCOUNT
  ################################
  PNM: {
    jetstream: enabled

    imports: [
      {
        stream {
          account: SYS
          subject: "$SYS.ACCOUNT.PNM.>"
        }
      }
    ]

    # USER dùng để gọi Auth Callout
    # auth-service user created via nsc
    users: [
      {
        nkey: UDYEW2MZL77X2DBXBOZF2XPD3ENQWALQRXPOKYQ2PFZIW2TDAPLJEH4C
      }
    ]
  }
}

################################
# SYSTEM ACCOUNT
################################
system_account: SYS

################################
# AUTH CALLOUT
################################
authorization {
  timeout: 5

  auth_callout {

    # 🔑 ACCOUNT PUBLIC KEY (PNM)
    # Must match NATS_ACCOUNT_SEED public key in .env
    issuer: ADQJVKRRWCB32QRIR6OL6WDSTOK6VLZCLI7Z3WGZWJCP2UFH4EXLHHJ6

    # User (nkey) được phép gọi callout
    # auth-service user: UDYEW2MZL77X2DBXBOZF2XPD3ENQWALQRXPOKYQ2PFZIW2TDAPLJEH4C
    auth_users: [
      UDYEW2MZL77X2DBXBOZF2XPD3ENQWALQRXPOKYQ2PFZIW2TDAPLJEH4C
    ]

    # Account chứa user được auth
    account: PNM

    # XKey để mã hoá request/response
    # Must match NATS_XKEY_SEED public key in .env
    xkey: XAVXJLXWZR7W24SAOPN6YATDOF2B6URA4GMBKYM7SBQIFO4O6OLQKSZB
  }
}